# Generated by Django 5.0.3 on 2024-03-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.RunSQL("""
                          INSERT INTO storefront.store_collection (title)
                          VALUES ('collection1')
                          """, """
                          DELETE FROM storefront.store_collection
                          WHERE title='collection1'
                          """)
        # Deletion triggers on reverting the migration
    ]
